/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bike {
  'id' : string,
  'status' : string,
  'todayEarnings' : bigint,
  'legalNo' : string,
  'monthEarnings' : bigint,
  'investedAmount' : bigint,
  'ownershipPercentage' : bigint,
}
export interface FamilyMember {
  'name' : string,
  'role' : string,
  'share' : bigint,
  'amount' : bigint,
}
export interface InvestorProfile {
  'city' : string,
  'familyMembers' : Array<FamilyMember>,
  'portfolioValue' : bigint,
  'bikes' : Array<Bike>,
  'totalPayout' : bigint,
  'totalBikes' : bigint,
  'payouts' : Array<Payout>,
  'investorName' : string,
}
export interface Payout {
  'status' : string,
  'date' : string,
  'investorShare' : bigint,
  'grossRevenue' : bigint,
  'bikeId' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDemoInvestors' : ActorMethod<[], Array<string>>,
  'getMyProfile' : ActorMethod<[], [] | [InvestorProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginAsDemo' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedDemoData' : ActorMethod<[], undefined>,
  'upsertMyProfile' : ActorMethod<[InvestorProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];